// 本文件由 scripts/fetch-icon-font.mjs 生成,请勿手改。
// 图标名扫自 design/project/NGA客户端.dc.html,码点取自 Material Icons Outlined(Apache-2.0)。

/**
 * 图标名 → 字体码点。字体本体是 assets/fonts/MaterialIconsOutlined-Regular.otf,
 * 由 src/ui/icon.tsx 加载后按码点渲染(不用连字,Android 上连字在部分 ROM 会失效)。
 *
 * 名字与设计稿里的 `class="ms"` 内容一一对应,加新图标就改设计稿后重跑脚本。
 */
export const ICON_GLYPHS = {
  account_tree: '\ue97a',
  add: '\ue145',
  alternate_email: '\ue0e6',
  android: '\ue859',
  arrow_back: '\ue5c4',
  arrow_forward: '\ue5c8',
  article: '\uef42',
  battery_full: '\ue1a4',
  block: '\ue14b',
  bookmark: '\ue866',
  cached: '\ue86a',
  campaign: '\uef49',
  chat_bubble: '\ue0ca',
  check_box: '\ue834',
  check_box_outline_blank: '\ue835',
  chevron_left: '\ue5cb',
  chevron_right: '\ue5cc',
  close: '\ue5cd',
  cloud_off: '\ue2c1',
  content_copy: '\uf08a',
  create_new_folder: '\ue2cc',
  dark_mode: '\ue51c',
  delete: '\ue872',
  delete_sweep: '\ue16c',
  devices: '\ue1b1',
  download: '\uf090',
  draw: '\ue746',
  edit: '\ue3c9',
  expand_more: '\ue5cf',
  filter_alt: '\uef4f',
  flag: '\ue153',
  folder: '\ue2c7',
  folder_open: '\ue2c8',
  folder_special: '\ue617',
  history: '\ue889',
  image: '\ue3f4',
  info: '\ue88e',
  keyboard: '\ue312',
  library_add: '\ue02e',
  local_fire_department: '\uef55',
  lock: '\ue897',
  logout: '\ue9ba',
  low_priority: '\ue16d',
  menu: '\ue5d2',
  more_horiz: '\ueae1',
  more_vert: '\ue5d4',
  north_east: '\uf1e1',
  notifications_active: '\ue7f7',
  open_in_browser: '\ue89d',
  person: '\ue7fd',
  person_add: '\ue7fe',
  phone_iphone: '\ue325',
  public: '\ue80b',
  push_pin: '\uf10d',
  radio_button_checked: '\ue837',
  radio_button_unchecked: '\ue836',
  refresh: '\ue5d5',
  remove: '\ue15b',
  reply: '\ue15e',
  save: '\ue161',
  search: '\ue8b6',
  send: '\ue163',
  sentiment_satisfied: '\ue813',
  settings: '\ue8b8',
  share: '\ue80d',
  signal_cellular_alt: '\ue202',
  smartphone: '\ue32c',
  sms: '\ue625',
  star: '\ue838',
  sticky_note_2: '\uf1fc',
  text_fields: '\ue262',
  thumb_down: '\ue8db',
  thumb_up: '\ue8dc',
  tune: '\ue429',
  warning: '\ue002',
  wifi: '\ue63e',
  workspace_premium: '\ue7af',
} as const;

export type IconName = keyof typeof ICON_GLYPHS;
