package com.chasel.ng2n.ui.bbcode

/**
 * 本文件由 `scripts/gen-smilies-kt.mjs` 生成,请勿手改。
 * 数据源:`src/core/smilies/table.generated.ts`(它本身由 `scripts/fetch-smilies.mjs`
 * 从 https://img4.nga.cn/common_res/js_bbscode_core.js 抓出来)。
 *
 * 7 个套系、265 个表情、265 个随包文件。
 * 图片在 `app/src/main/assets/smilies/`,文件名即 CDN 原名。
 */

/** 一个套系。`entries` 的顺序与官方表一致(表情面板按此排列)。 */
data class SmileyCategory(
  /** BBCode 里的分类标识,如 `ac`;`"0"` 是 `[s:数字]` 用的默认套。 */
  val key: String,
  /** 官方套系中文名,如 `AC娘(v1)`。 */
  val label: String,
  /** `名称 to 文件名`。 */
  val entries: List<Pair<String, String>>,
)

/** CDN 上表情图所在目录,远程兜底 URL 的前缀。 */
const val SMILEY_BASE_URL: String = "https://img4.nga.cn/ngabbs/post/smile"

/** 官方表里的套系顺序。 */
val SMILEY_CATEGORIES: List<SmileyCategory> = listOf(
  SmileyCategory(
    key = "0",
    label = "默认",
    entries = listOf(
      "1" to "smile.gif",
      "2" to "mrgreen.gif",
      "3" to "question.gif",
      "4" to "wink.gif",
      "5" to "redface.gif",
      "6" to "sad.gif",
      "7" to "cool.gif",
      "8" to "crazy.gif",
      "32" to "12.gif",
      "33" to "13.gif",
      "34" to "14.gif",
      "30" to "10.gif",
      "29" to "09.gif",
      "28" to "08.gif",
      "27" to "07.gif",
      "26" to "06.gif",
      "25" to "05.gif",
      "24" to "04.gif",
      "35" to "15.gif",
      "36" to "16.gif",
      "37" to "17.gif",
      "38" to "18.gif",
      "39" to "19.gif",
      "40" to "20.gif",
      "41" to "21.gif",
      "42" to "22.gif",
      "43" to "23.gif",
    ),
  ),
  SmileyCategory(
    key = "ac",
    label = "AC娘(v1)",
    entries = listOf(
      "blink" to "ac0.png",
      "goodjob" to "ac1.png",
      "上" to "ac2.png",
      "中枪" to "ac3.png",
      "偷笑" to "ac4.png",
      "冷" to "ac5.png",
      "凌乱" to "ac6.png",
      "吓" to "ac8.png",
      "吻" to "ac9.png",
      "呆" to "ac10.png",
      "咦" to "ac11.png",
      "哦" to "ac12.png",
      "哭" to "ac13.png",
      "哭1" to "ac14.png",
      "哭笑" to "ac15.png",
      "喘" to "ac17.png",
      "心" to "ac23.png",
      "囧" to "ac21.png",
      "晕" to "ac33.png",
      "汗" to "ac34.png",
      "瞎" to "ac35.png",
      "羞" to "ac36.png",
      "羡慕" to "ac37.png",
      "委屈" to "ac22.png",
      "忧伤" to "ac24.png",
      "怒" to "ac25.png",
      "怕" to "ac26.png",
      "惊" to "ac27.png",
      "愁" to "ac28.png",
      "抓狂" to "ac29.png",
      "哼" to "ac16.png",
      "喷" to "ac18.png",
      "嘲笑" to "ac19.png",
      "嘲笑1" to "ac20.png",
      "抠鼻" to "ac30.png",
      "无语" to "ac32.png",
      "衰" to "ac40.png",
      "黑枪" to "ac44.png",
      "花痴" to "ac38.png",
      "闪光" to "ac43.png",
      "擦汗" to "ac31.png",
      "茶" to "ac39.png",
      "计划通" to "ac41.png",
      "反对" to "ac7.png",
      "赞同" to "ac42.png",
    ),
  ),
  SmileyCategory(
    key = "a2",
    label = "AC娘(v2)",
    entries = listOf(
      "goodjob" to "a2_02.png",
      "诶嘿" to "a2_05.png",
      "偷笑" to "a2_03.png",
      "怒" to "a2_04.png",
      "笑" to "a2_07.png",
      "那个…" to "a2_08.png",
      "哦嗬嗬嗬" to "a2_09.png",
      "舔" to "a2_10.png",
      "鬼脸" to "a2_14.png",
      "冷" to "a2_16.png",
      "大哭" to "a2_15.png",
      "哭" to "a2_17.png",
      "恨" to "a2_21.png",
      "中枪" to "a2_23.png",
      "囧" to "a2_24.png",
      "你看看你" to "a2_25.png",
      "doge" to "a2_27.png",
      "自戳双目" to "a2_28.png",
      "偷吃" to "a2_30.png",
      "冷笑" to "a2_31.png",
      "壁咚" to "a2_32.png",
      "不活了" to "a2_33.png",
      "不明觉厉" to "a2_36.png",
      "是在下输了" to "a2_51.png",
      "你为猴这么" to "a2_53.png",
      "干杯" to "a2_54.png",
      "干杯2" to "a2_55.png",
      "异议" to "a2_47.png",
      "认真" to "a2_48.png",
      "你已经死了" to "a2_45.png",
      "你这种人…" to "a2_49.png",
      "妮可妮可妮" to "a2_18.png",
      "惊" to "a2_19.png",
      "抢镜头" to "a2_52.png",
      "yes" to "a2_26.png",
      "有何贵干" to "a2_11.png",
      "病娇" to "a2_12.png",
      "lucky" to "a2_13.png",
      "poi" to "a2_20.png",
      "囧2" to "a2_22.png",
      "威吓" to "a2_42.png",
      "jojo立" to "a2_37.png",
      "jojo立2" to "a2_38.png",
      "jojo立3" to "a2_39.png",
      "jojo立4" to "a2_41.png",
      "jojo立5" to "a2_40.png",
    ),
  ),
  SmileyCategory(
    key = "ng",
    label = "NG娘",
    entries = listOf(
      "呲牙笑" to "ng_1.png",
      "奸笑" to "ng_2.png",
      "问号" to "ng_3.png",
      "茶" to "ng_4.png",
      "笑指" to "ng_5.png",
      "燃尽" to "ng_6.png",
      "晕" to "ng_7.png",
      "扇笑" to "ng_8.png",
      "寄" to "ng_9.png",
      "别急" to "ng_10.png",
      "doge" to "ng_11.png",
      "丧" to "ng_12.png",
      "汗" to "ng_13.png",
      "叹气" to "ng_15.png",
      "吃饼" to "ng_16.png",
      "吃瓜" to "ng_17.png",
      "吐舌" to "ng_18.png",
      "哭" to "ng_19.png",
      "喘" to "ng_20.png",
      "心" to "ng_21.png",
      "喷" to "ng_22.png",
      "困" to "ng_24.png",
      "大哭" to "ng_25.png",
      "大惊" to "ng_26.png",
      "害怕" to "ng_27.png",
      "惊" to "ng_28.png",
      "暴怒" to "ng_30.png",
      "气愤" to "ng_31.png",
      "热" to "ng_32.png",
      "瓜不熟" to "ng_33.png",
      "瞎" to "ng_34.png",
      "色" to "ng_35.png",
      "斜眼" to "ng_37.png",
      "问号大" to "ng_38.png",
    ),
  ),
  SmileyCategory(
    key = "pst",
    label = "潘斯特",
    entries = listOf(
      "举手" to "pt00.png",
      "亲" to "pt01.png",
      "偷笑" to "pt02.png",
      "偷笑2" to "pt03.png",
      "偷笑3" to "pt04.png",
      "傻眼" to "pt05.png",
      "傻眼2" to "pt06.png",
      "兔子" to "pt07.png",
      "发光" to "pt08.png",
      "呆" to "pt09.png",
      "呆2" to "pt10.png",
      "呆3" to "pt11.png",
      "呕" to "pt12.png",
      "呵欠" to "pt13.png",
      "哭" to "pt14.png",
      "哭2" to "pt15.png",
      "哭3" to "pt16.png",
      "嘲笑" to "pt17.png",
      "基" to "pt18.png",
      "宅" to "pt19.png",
      "安慰" to "pt20.png",
      "幸福" to "pt21.png",
      "开心" to "pt22.png",
      "开心2" to "pt23.png",
      "开心3" to "pt24.png",
      "怀疑" to "pt25.png",
      "怒" to "pt26.png",
      "怒2" to "pt27.png",
      "怨" to "pt28.png",
      "惊吓" to "pt29.png",
      "惊吓2" to "pt30.png",
      "惊呆" to "pt31.png",
      "惊呆2" to "pt32.png",
      "惊呆3" to "pt33.png",
      "惨" to "pt34.png",
      "斜眼" to "pt35.png",
      "晕" to "pt36.png",
      "汗" to "pt37.png",
      "泪" to "pt38.png",
      "泪2" to "pt39.png",
      "泪3" to "pt40.png",
      "泪4" to "pt41.png",
      "满足" to "pt42.png",
      "满足2" to "pt43.png",
      "火星" to "pt44.png",
      "牙疼" to "pt45.png",
      "电击" to "pt46.png",
      "看戏" to "pt47.png",
      "眼袋" to "pt48.png",
      "眼镜" to "pt49.png",
      "笑而不语" to "pt50.png",
      "紧张" to "pt51.png",
      "美味" to "pt52.png",
      "背" to "pt53.png",
      "脸红" to "pt54.png",
      "脸红2" to "pt55.png",
      "腐" to "pt56.png",
      "星星眼" to "pt57.png",
      "谢" to "pt58.png",
      "醉" to "pt59.png",
      "闷" to "pt60.png",
      "闷2" to "pt61.png",
      "音乐" to "pt62.png",
      "黑脸" to "pt63.png",
      "鼻血" to "pt64.png",
    ),
  ),
  SmileyCategory(
    key = "dt",
    label = "外域三人组",
    entries = listOf(
      "ROLL" to "dt01.png",
      "上" to "dt02.png",
      "傲娇" to "dt03.png",
      "叉出去" to "dt04.png",
      "发光" to "dt05.png",
      "呵欠" to "dt06.png",
      "哭" to "dt07.png",
      "啃古头" to "dt08.png",
      "嘲笑" to "dt09.png",
      "心" to "dt10.png",
      "怒" to "dt11.png",
      "怒2" to "dt12.png",
      "怨" to "dt13.png",
      "惊" to "dt14.png",
      "惊2" to "dt15.png",
      "无语" to "dt16.png",
      "星星眼" to "dt17.png",
      "星星眼2" to "dt18.png",
      "晕" to "dt19.png",
      "注意" to "dt20.png",
      "注意2" to "dt21.png",
      "泪" to "dt22.png",
      "泪2" to "dt23.png",
      "烧" to "dt24.png",
      "笑" to "dt25.png",
      "笑2" to "dt26.png",
      "笑3" to "dt27.png",
      "脸红" to "dt28.png",
      "药" to "dt29.png",
      "衰" to "dt30.png",
      "鄙视" to "dt31.png",
      "闲" to "dt32.png",
      "黑脸" to "dt33.png",
    ),
  ),
  SmileyCategory(
    key = "pg",
    label = "企鹅",
    entries = listOf(
      "战斗力" to "pg01.png",
      "哈啤" to "pg02.png",
      "满分" to "pg03.png",
      "衰" to "pg04.png",
      "拒绝" to "pg05.png",
      "心" to "pg06.png",
      "严肃" to "pg07.png",
      "吃瓜" to "pg08.png",
      "嘣" to "pg09.png",
      "嘣2" to "pg10.png",
      "冻" to "pg11.png",
      "谢" to "pg12.png",
      "哭" to "pg13.png",
      "响指" to "pg14.png",
      "转身" to "pg15.png",
    ),
  ),
)

/** 实际随包下载成功的文件名。表里有、这里没有的走远程 URL。 */
val BUNDLED_SMILEY_FILES: Set<String> = setOf(
  "smile.gif",
  "mrgreen.gif",
  "question.gif",
  "wink.gif",
  "redface.gif",
  "sad.gif",
  "cool.gif",
  "crazy.gif",
  "12.gif",
  "13.gif",
  "14.gif",
  "10.gif",
  "09.gif",
  "08.gif",
  "07.gif",
  "06.gif",
  "05.gif",
  "04.gif",
  "15.gif",
  "16.gif",
  "17.gif",
  "18.gif",
  "19.gif",
  "20.gif",
  "21.gif",
  "22.gif",
  "23.gif",
  "ac0.png",
  "ac1.png",
  "ac2.png",
  "ac3.png",
  "ac4.png",
  "ac5.png",
  "ac6.png",
  "ac8.png",
  "ac9.png",
  "ac10.png",
  "ac11.png",
  "ac12.png",
  "ac13.png",
  "ac14.png",
  "ac15.png",
  "ac17.png",
  "ac23.png",
  "ac21.png",
  "ac33.png",
  "ac34.png",
  "ac35.png",
  "ac36.png",
  "ac37.png",
  "ac22.png",
  "ac24.png",
  "ac25.png",
  "ac26.png",
  "ac27.png",
  "ac28.png",
  "ac29.png",
  "ac16.png",
  "ac18.png",
  "ac19.png",
  "ac20.png",
  "ac30.png",
  "ac32.png",
  "ac40.png",
  "ac44.png",
  "ac38.png",
  "ac43.png",
  "ac31.png",
  "ac39.png",
  "ac41.png",
  "ac7.png",
  "ac42.png",
  "a2_02.png",
  "a2_05.png",
  "a2_03.png",
  "a2_04.png",
  "a2_07.png",
  "a2_08.png",
  "a2_09.png",
  "a2_10.png",
  "a2_14.png",
  "a2_16.png",
  "a2_15.png",
  "a2_17.png",
  "a2_21.png",
  "a2_23.png",
  "a2_24.png",
  "a2_25.png",
  "a2_27.png",
  "a2_28.png",
  "a2_30.png",
  "a2_31.png",
  "a2_32.png",
  "a2_33.png",
  "a2_36.png",
  "a2_51.png",
  "a2_53.png",
  "a2_54.png",
  "a2_55.png",
  "a2_47.png",
  "a2_48.png",
  "a2_45.png",
  "a2_49.png",
  "a2_18.png",
  "a2_19.png",
  "a2_52.png",
  "a2_26.png",
  "a2_11.png",
  "a2_12.png",
  "a2_13.png",
  "a2_20.png",
  "a2_22.png",
  "a2_42.png",
  "a2_37.png",
  "a2_38.png",
  "a2_39.png",
  "a2_41.png",
  "a2_40.png",
  "ng_1.png",
  "ng_2.png",
  "ng_3.png",
  "ng_4.png",
  "ng_5.png",
  "ng_6.png",
  "ng_7.png",
  "ng_8.png",
  "ng_9.png",
  "ng_10.png",
  "ng_11.png",
  "ng_12.png",
  "ng_13.png",
  "ng_15.png",
  "ng_16.png",
  "ng_17.png",
  "ng_18.png",
  "ng_19.png",
  "ng_20.png",
  "ng_21.png",
  "ng_22.png",
  "ng_24.png",
  "ng_25.png",
  "ng_26.png",
  "ng_27.png",
  "ng_28.png",
  "ng_30.png",
  "ng_31.png",
  "ng_32.png",
  "ng_33.png",
  "ng_34.png",
  "ng_35.png",
  "ng_37.png",
  "ng_38.png",
  "pt00.png",
  "pt01.png",
  "pt02.png",
  "pt03.png",
  "pt04.png",
  "pt05.png",
  "pt06.png",
  "pt07.png",
  "pt08.png",
  "pt09.png",
  "pt10.png",
  "pt11.png",
  "pt12.png",
  "pt13.png",
  "pt14.png",
  "pt15.png",
  "pt16.png",
  "pt17.png",
  "pt18.png",
  "pt19.png",
  "pt20.png",
  "pt21.png",
  "pt22.png",
  "pt23.png",
  "pt24.png",
  "pt25.png",
  "pt26.png",
  "pt27.png",
  "pt28.png",
  "pt29.png",
  "pt30.png",
  "pt31.png",
  "pt32.png",
  "pt33.png",
  "pt34.png",
  "pt35.png",
  "pt36.png",
  "pt37.png",
  "pt38.png",
  "pt39.png",
  "pt40.png",
  "pt41.png",
  "pt42.png",
  "pt43.png",
  "pt44.png",
  "pt45.png",
  "pt46.png",
  "pt47.png",
  "pt48.png",
  "pt49.png",
  "pt50.png",
  "pt51.png",
  "pt52.png",
  "pt53.png",
  "pt54.png",
  "pt55.png",
  "pt56.png",
  "pt57.png",
  "pt58.png",
  "pt59.png",
  "pt60.png",
  "pt61.png",
  "pt62.png",
  "pt63.png",
  "pt64.png",
  "dt01.png",
  "dt02.png",
  "dt03.png",
  "dt04.png",
  "dt05.png",
  "dt06.png",
  "dt07.png",
  "dt08.png",
  "dt09.png",
  "dt10.png",
  "dt11.png",
  "dt12.png",
  "dt13.png",
  "dt14.png",
  "dt15.png",
  "dt16.png",
  "dt17.png",
  "dt18.png",
  "dt19.png",
  "dt20.png",
  "dt21.png",
  "dt22.png",
  "dt23.png",
  "dt24.png",
  "dt25.png",
  "dt26.png",
  "dt27.png",
  "dt28.png",
  "dt29.png",
  "dt30.png",
  "dt31.png",
  "dt32.png",
  "dt33.png",
  "pg01.png",
  "pg02.png",
  "pg03.png",
  "pg04.png",
  "pg05.png",
  "pg06.png",
  "pg07.png",
  "pg08.png",
  "pg09.png",
  "pg10.png",
  "pg11.png",
  "pg12.png",
  "pg13.png",
  "pg14.png",
  "pg15.png",
)
